name: First Workflow

on: workflow_dispatch

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: |
          echo "Hello World!"
          echo "Haste Dir gedacht!"
      - name: Print goodbye
        run: echo "Done - bye!"
      - name: Get the environment
        run: env | grep GITHUB
      - name: Print Org Name
        run: |
          echo "${GH_ORGANIZATION}"
          echo $vars.GH_ORGANIZATION
